#!/bin/sh

[ -e /scripts/imgldr_functions ] && . /scripts/imgldr_functions

mount_root_fs()
{
  local lowerdir
  local upperdir
  local workdir

  # Check needed modules
  if ! modprobe overlay; then
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "   Failed to load overlayfs" "        kernel module"
  fi

  # Mount the final root filesystem overlay at ${rootmnt} and handle different modes
  mkdir -p /kiosk_overlay
  if [ "$IMGLDR_MODE" = "DEVELOPER" ]; then
    imgldr_pretty_text "       !!! WARNING !!!" "  YOU ARE IN DEVELOPER MODE!" "  Changes here will be saved" " separated from other modes!" 
    lowerdir="/kiosk_overlay/:${SQFS_MOUNT}/SYSTEM"
    upperdir="${ROOT_MOUNT}/USERDATA/DEVELOPER/data"
    workdir="${ROOT_MOUNT}/USERDATA/DEVELOPER/work"
    mkdir -p "${upperdir}" "${workdir}"
    if ! mount -t overlay overlay \
        -o lowerdir="${lowerdir}",upperdir="${upperdir}",workdir="${workdir}" "${rootmnt}"; then
      imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "  Failed to mount overlayfs" " as root overlay file system"
    fi
  elif [ "$IMGLDR_MODE" != "RAMDISK" ] || [ "$IMGLDR_MODE" != "STORED" ]; then
    lowerdir="/kiosk_overlay/:${SQFS_MOUNT}/SYSTEM"
    if ! mount -t overlay overlay \
        -o lowerdir="${lowerdir}" "${rootmnt}"; then
      imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "  Failed to mount overlayfs" " as root overlay file system"
    fi
    if [ "$IMGLDR_MODE" != "RAMDISK" ]; then
      mkdir -p /mnt/ramstorage
      mount -t tmpfs tmpfs "/mnt/ramstorage"
      mkdir -p "${ROOT_MOUNT}/USERDATA/OVERLAY/data"
      lowerdir="${ROOT_MOUNT}/USERDATA/OVERLAY/data:${rootmnt}/var"
      upperdir="/mnt/ramstorage/data"
      workdir="/mnt/ramstorage/work"
    else
      lowerdir="${rootmnt}/var"
      upperdir="${ROOT_MOUNT}/USERDATA/OVERLAY/data"
      workdir="${ROOT_MOUNT}/USERDATA/OVERLAY/work"
    fi
    mkdir -p "${upperdir}" "${workdir}"
    if ! mount -t overlay overlay \
        -o lowerdir="${lowerdir}",upperdir="${upperdir}",workdir="${workdir}" "${rootmnt}/var"; then
      imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "  Failed to mount overlayfs" " as var overlay file system"
    fi
  else
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "      Invalid mode set!" "$IMGLDR_MODE" "   could not boot properly!"
    sleep 3.0
  fi
}

mount_root_fs

exit 0
