#!/bin/sh

[ -e /scripts/imgldr_functions ] && . /scripts/imgldr_functions
[ -e /conf/param.conf ] && . /conf/param.conf

repair_bootfs() {
  local restored_boot
  local filepath
  local filename
  #Restore boot partition if needed
  if [ "$IMGLDR_MODE" != "DEVELOPER" ]; then
    if [ -d ${SQFS_MOUNT}/BOOT ]; then
      for filepath in ${SQFS_MOUNT}/BOOT/*; do
        filename=$(basename "${filepath}")
        if [ -f "${filepath}" ] && ! diff "${filepath}" "${BOOT_MOUNT}/${filename}" >/dev/null 2>&1; then
          [ -z "${restored_boot}" ] && imgldr_pretty_text "Restore boot partition data..." "      Then Rebooting..." "" && echo " "
          cp -f "${filepath}" "${BOOT_MOUNT}/${filename}"
          restored_boot="yes"
        fi
      done
      for filepath in ${SQFS_MOUNT}/BOOT/overlays/*; do
        filename=$(basename "${filepath}")
        if [ -f "${filepath}" ] && ! diff "${filepath}" "${BOOT_MOUNT}/overlays/${filename}" >/dev/null 2>&1; then
          [ -z "${restored_boot}" ] && imgldr_pretty_text "Restore boot partition data..." "      Then Rebooting..." "" && echo " "
          cp -f "${filepath}" "${BOOT_MOUNT}/overlays/${filename}"
          restored_boot="yes"
        fi
      done
      [ -n "${restored_boot}" ] && imgldr_do_reboot
    else
      imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "    BOOT folder not found!" "   boot partition might be" "          outdated..." "${BOOT_DEV}"
    fi
  fi
}

build_dirs() {
  # Create directories for overlay mountpoints
  mkdir -p /mnt/overlay/developer /mnt/overlay/etc /mnt/overlay/home /mnt/overlay/var
  # Build rootfs base directory structure
  mkdir -p ${ROOT_MOUNT}/CONFIG ${ROOT_MOUNT}/IMAGES ${ROOT_MOUNT}/USERDATA ${ROOT_MOUNT}/STATIC
  mkdir -p ${ROOT_MOUNT}/USERDATA/PERSIST_RAM ${ROOT_MOUNT}/USERDATA/OVERLAY ${ROOT_MOUNT}/USERDATA/DEVELOPER
  chown -fR 0:0 ${ROOT_MOUNT}/CONFIG ${ROOT_MOUNT}/IMAGES ${ROOT_MOUNT}/STATIC
  chmod -fR u=rwX,g=rX,o=rX ${ROOT_MOUNT}/CONFIG ${ROOT_MOUNT}/IMAGES
  chmod -fR u=rwX,g=X,o=X ${ROOT_MOUNT}/STATIC
  chown -f 0:0 ${ROOT_MOUNT}/USERDATA
  chmod -f u=rwX,g=rX,o=rX ${ROOT_MOUNT}/USERDATA
  chown -f 0:0 ${ROOT_MOUNT}/USERDATA/PERSIST_RAM
  chmod -f u=rwX,g=rwX,o=rX ${ROOT_MOUNT}/USERDATA/PERSIST_RAM
  chown -f 0:0 ${ROOT_MOUNT}/USERDATA/OVERLAY
  chmod -f u=rwX,g=rX,o=rX ${ROOT_MOUNT}/USERDATA/OVERLAY
  chown -f 0:0 ${ROOT_MOUNT}/USERDATA/DEVELOPER
  chmod -f u=rwX,g=rX,o=rX ${ROOT_MOUNT}/USERDATA/DEVELOPER
}

mount_root_fs()
{
  local attempt
  local filepath
  local filename
  local response


  # Mount the overlay in /mnt/overlay
  if [ -z "${DEVMODE}" ] || [ -n "${FIRSTBOOT}" ]; then
    if [ -n "${SAVEDBOOT}" ]; then
      mount -o bind ${ROOT_MOUNT}/OVERLAY /mnt/overlay
      echo "1" > ${ROOT_MOUNT}/STATIC/savedboot
    else
      mount -t tmpfs tmpfs /mnt/overlay
      [ -f ${ROOT_MOUNT}/STATIC/savedboot ] && RESET_OFS=y
    fi
    [ -f ${ROOT_MOUNT}/STATIC/setupboot ] && RESET_OFS=y
    if [ -n "${RESET_OFS}" ] || [ -n "${RESET_ALL}" ]; then
      imgldr_pretty_text "" " ...Restoring factory data..." ""
      echo " "
      ls "${ROOT_MOUNT}/OVERLAY/"* >/dev/null 2>&1 && echo "Delete saved overlay data..." && find ${ROOT_MOUNT}/OVERLAY -maxdepth 1 -mindepth 1 -exec rm -rf {} \;
      [ -e ${ROOT_MOUNT}/SETUP ] && echo "Delete saved SETUP data..." && rm -rf ${ROOT_MOUNT}/SETUP
      [ -n "${RESET_ALL}" ] && ls "${ROOT_MOUNT}/STORAGE/"* >/dev/null 2>&1 && echo "Delete STORAGE data..." && find ${ROOT_MOUNT}/STORAGE -maxdepth 1 -mindepth 1 -exec rm -rf {} \;
      [ -f ${ROOT_MOUNT}/STATIC/savedboot ] && rm -f ${ROOT_MOUNT}/STATIC/savedboot
      [ -f ${ROOT_MOUNT}/STATIC/setupboot ] && rm -f ${ROOT_MOUNT}/STATIC/setupboot
      sed -i 's|RESET_OFS[^ ]* \{0,1\}||g' ${BOOT_MOUNT}/cmdline.txt >/dev/null 2>&1
      sed -i 's|RESET_ALL[^ ]* \{0,1\}||g' ${BOOT_MOUNT}/cmdline.txt >/dev/null 2>&1
      sed -i 's|[ \t]*$||' ${BOOT_MOUNT}/cmdline.txt
      echo "... FINISHED! Continue booting..."
    fi
  elif [ -n "${DEVMODE}" ]; then
    imgldr_pretty_text "       !!! WARNING !!!" "     YOU ARE IN SETUP MODE" ""
    echo " "
    [ -f ${ROOT_MOUNT}/IMAGES/oem.sqfs ] && echo "INFO: oem.sqfs image file is ignored in this mode!"
    if [ -n "${DEVMODE}" ] && [ -n "${SAVEDBOOT}" ]; then
      echo "Exiting saved boot..."
      sed -i 's|SAVEDBOOT[^ ]* \{0,1\}||g' ${BOOT_MOUNT}/cmdline.txt >/dev/null 2>&1
      sed -i 's|[ \t]*$||' ${BOOT_MOUNT}/cmdline.txt
      ls "${ROOT_MOUNT}/OVERLAY/"* >/dev/null 2>&1 && echo "Delete saved overlay data..." && find ${ROOT_MOUNT}/OVERLAY -maxdepth 1 -mindepth 1 -exec rm -rf {} \;
      [ -f ${ROOT_MOUNT}/STATIC/savedboot ] && rm -f ${ROOT_MOUNT}/STATIC/savedboot
      sync >/dev/null 2>&1
      umount /mnt/overlay >/dev/null 2>&1
      umount /mnt/oemimg >/dev/null 2>&1
      umount /mnt/sysimg >/dev/null 2>&1
      umount ${ROOT_MOUNT} >/dev/null 2>&1
      umount ${BOOT_MOUNT} >/dev/null 2>&1
      echo "Rebooting in 5 seconds..."
      sleep 5
      reboot -f
    fi
    echo "1" > ${ROOT_MOUNT}/STATIC/setupboot
    mkdir -p ${ROOT_MOUNT}/SETUP
    if ls "${ROOT_MOUNT}/SETUP/"* >/dev/null 2>&1; then
      response="x"
      echo "SETUP data was found! what would you like to do with that?"
      echo "ignore? (i), remove? (r), exit DEVMODE? (e), console? (c), finish it and poweroff? (f)"
      while [ "${response}" != "i" ] && [ "${response}" != "r" ] && [ "${response}" != "e" ] && [ "${response}" != "c" ] && [ "${response}" != "f" ]; do
        read -n 1 -s response
      done
      if [ "$response" = "i" ]; then
        echo " "
        echo "Ignoring data and continue boot..."
      fi
      if [ "$response" = "r" ]; then
        echo " "
        echo "Delete saved SETUP data..."
        [ -e ${ROOT_MOUNT}/SETUP ] && rm -rf ${ROOT_MOUNT}/SETUP
        mkdir -p ${ROOT_MOUNT}/SETUP
      fi
      if [ "$response" = "e" ]; then
        echo " "
        echo "Exiting DEVMODE..."
        sed -i 's|DEVMODE[^ ]* \{0,1\}||g' ${BOOT_MOUNT}/cmdline.txt >/dev/null 2>&1
        sed -i 's|[ \t]*$||' ${BOOT_MOUNT}/cmdline.txt
        [ -e ${ROOT_MOUNT}/SETUP ] && rm -rf ${ROOT_MOUNT}/SETUP
      fi
      if [ "$response" = "f" ]; then
        echo " "
        echo "Check OEM Setup data..."
        if ls "${ROOT_MOUNT}/SETUP/data/"* >/dev/null 2>&1; then
          if [ -e ${ROOT_MOUNT}/OEM ]; then
            echo "Old OEM folder was found! what would you like to do?"
            echo "remove? (r), console? (c), abort? (a)"
            while [ "${response}" != "r" ] && [ "${response}" != "a" ] && [ "${response}" != "c" ]; do
              read -n 1 -s response
            done
            if [ "$response" = "r" ]; then
              echo "Delete old OEM folder..."
              rm -rf ${ROOT_MOUNT}/OEM
              response="f"
            elif [ "$response" = "a" ]; then
              echo "Abort..."
            fi
          fi
          if [ "$response" = "f" ]; then
            echo "Prepare OEM folder..."
            mv -f ${ROOT_MOUNT}/SETUP/data ${ROOT_MOUNT}/OEM
            rm -rf ${ROOT_MOUNT}/SETUP
          fi
        fi
      fi
      if [ "$response" = "c" ]; then
        imgldr_shell_console
      fi
      sync >/dev/null 2>&1
      if [ "$response" != "i" ]; then
        umount /mnt/overlay >/dev/null 2>&1
        umount /mnt/oemimg >/dev/null 2>&1
        umount /mnt/sysimg >/dev/null 2>&1
        umount ${ROOT_MOUNT} >/dev/null 2>&1
        umount ${BOOT_MOUNT} >/dev/null 2>&1
      fi
      if [ "$response" != "i" ] && [ "$response" != "f" ]; then
        echo "Rebooting in 5 seconds..."
        sleep 5
        reboot -f
      fi
      if [ "$response" = "f" ]; then
        echo "Power off in 5 seconds..."
        sleep 5
        poweroff -f
      fi
    fi
    mount -o bind ${ROOT_MOUNT}/SETUP /mnt/overlay
    sleep 3
  fi
  [ -d /mnt/overlay/work ] && rm -rf /mnt/overlay/work
  mkdir -p /mnt/overlay/data /mnt/overlay/work

  # Mount the final overlay-root in $rootmnt
  if ! mount -t overlay \
     -olowerdir=${overlay_mnt},upperdir=/mnt/overlay/data,workdir=/mnt/overlay/work \
     overlay ${rootmnt}; then
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "  Failed to mount overlayfs" " as root overlay file system"
  fi

  #copy version info to overlay
  mkdir -p ${rootmnt}/etc/imageinfo
  [ -f /mnt/sysimg/INFO/sysinfo ] && cp -f /mnt/sysimg/INFO/sysinfo ${rootmnt}/etc/imageinfo/sysinfo
  [ -f /mnt/oemimg/INFO/oeminfo ] && cp -f /mnt/oemimg/INFO/oeminfo ${rootmnt}/etc/imageinfo/oeminfo
  [ -f /mnt/sysimg/INFO/updateserver ] && cp -f /mnt/sysimg/INFO/updateserver ${rootmnt}/etc/imageinfo/updateserver

  # Configuring fstab in overlay
  mkdir -p ${rootmnt}/mnt/rootfs
  rm -rf ${rootmnt}/STORAGE ${rootmnt}/IMAGES ${rootmnt}/CONFIG ${rootmnt}/STATIC
  mkdir -p ${rootmnt}/STORAGE ${rootmnt}/IMAGES ${rootmnt}/CONFIG ${rootmnt}/STATIC
  chown -f 0:0 ${rootmnt}/STORAGE ${rootmnt}/IMAGES ${rootmnt}/CONFIG ${rootmnt}/STATIC
  chmod -f u=rwX,g=rwX,o=rwX ${rootmnt}/STORAGE
  chmod -f u=rwX,g=rX,o=rX ${rootmnt}/IMAGES ${rootmnt}/CONFIG ${rootmnt}/STATIC

  local fstab_boot=$(cat ${rootmnt}/etc/fstab 2>/dev/null)
  [ -z "${fstab_boot##*\/boot\/firmware*}" ] && boot_dir="/boot/firmware" || boot_dir="/boot"
  echo "proc                   /proc           proc    defaults                      0       0" > ${rootmnt}/etc/fstab
  echo "${BOOT_DEV}            ${boot_dir}     vfat    defaults                      0       0" >> ${rootmnt}/etc/fstab
  echo "${ROOT_DEV}            /mnt/rootfs     ${FSTYPE}    defaults,noatime         0       0" >> ${rootmnt}/etc/fstab
  echo "/mnt/rootfs/STORAGE    /STORAGE        auto    defaults,noatime,bind         0       0" >> ${rootmnt}/etc/fstab
  echo "/mnt/rootfs/IMAGES     /IMAGES         auto    defaults,noatime,bind         0       0" >> ${rootmnt}/etc/fstab
  echo "/mnt/rootfs/CONFIG     /CONFIG         auto    defaults,noatime,bind         0       0" >> ${rootmnt}/etc/fstab
  echo "/mnt/rootfs/STATIC     /STATIC         auto    defaults,noatime,bind         0       0" >> ${rootmnt}/etc/fstab

}

imgldr_check_fs
repair_bootfs
build_dirs
mount_root_fs

exit 0
