#!/bin/sh

[ -e /scripts/imgldr_functions ] && . /scripts/imgldr_functions || exit 1

IMGLDR_MODE="RAMDISK"
IMGLDR_RESET="NONE"
SYS_MOUNT="/mnt/sys_final"
FIRSTBOOT="NO"

get_variables() {
  if [ -f "${ROOT_MOUNT}/CONFIG/mode" ]; then
    IMGLDR_MODE="$(cat "${ROOT_MOUNT}/CONFIG/mode" 2>/dev/null)"
    if [ "$IMGLDR_MODE" != "RAMDISK" ] && [ "$IMGLDR_MODE" != "DEVELOPER" ] && [ "$IMGLDR_MODE" != "STORED" ]; then
      imgldr_pretty_text "     !!! CONFIG ERROR !!!" "   Invalid mode in config!" "   Defaulting to RAMDISK mode!"
      sleep 3.0
      IMGLDR_MODE="RAMDISK"
    fi
  fi
  if [ -f "${ROOT_MOUNT}/CONFIG/reset" ]; then
    IMGLDR_RESET="$(cat "${ROOT_MOUNT}/CONFIG/reset" 2>/dev/null)"
    if [ "$IMGLDR_RESET" != "USER" ] && [ "$IMGLDR_RESET" != "CONFIG" ] && 
       [ "$IMGLDR_RESET" != "ALL" ] && [ "$IMGLDR_RESET" != "NONE" ]; then
      imgldr_pretty_text "     !!! CONFIG ERROR !!!" "   Invalid reset in config!" "   Ignoring USER reset!"
      sleep 3.0
      IMGLDR_RESET="NONE"
    fi
  fi
  for x in $(cat /proc/cmdline)
  do
    case $x in
      FIRSTBOOT|*firstboot*|resize)
        FIRSTBOOT="YES"
      ;;
    esac
  done
  mkdir -p /conf
  touch /conf/param.conf
  echo "IMGLDR_MODE=$IMGLDR_MODE" >> "/conf/param.conf"
  echo "IMGLDR_RESET=$IMGLDR_RESET" >> "/conf/param.conf"
  echo "FIRSTBOOT=$FIRSTBOOT" >> "/conf/param.conf"
  echo "SYS_MOUNT=$SYS_MOUNT" >> "/conf/param.conf"
}

repair_bootfs() {
  local restored_boot
  local filepath
  local filename
  if [ "$IMGLDR_MODE" != "DEVELOPER" ]; then
    if [ -d ${SQFS_MOUNT}/BOOT ]; then
      for filepath in ${SQFS_MOUNT}/BOOT/*; do
        filename=$(basename "${filepath}")
        if [ -f "${filepath}" ] && ! diff "${filepath}" "${BOOT_MOUNT}/${filename}" >/dev/null 2>&1; then
          [ -z "${restored_boot}" ] && imgldr_pretty_text "Restore boot partition data..." "      Then Rebooting..."
          cp -f "${filepath}" "${BOOT_MOUNT}/${filename}"
          restored_boot="yes"
        fi
      done
      for filepath in ${SQFS_MOUNT}/BOOT/overlays/*; do
        filename=$(basename "${filepath}")
        if [ -f "${filepath}" ] && ! diff "${filepath}" "${BOOT_MOUNT}/overlays/${filename}" >/dev/null 2>&1; then
          [ -z "${restored_boot}" ] && imgldr_pretty_text "Restore boot partition data..." "      Then Rebooting..."
          cp -f "${filepath}" "${BOOT_MOUNT}/overlays/${filename}"
          restored_boot="yes"
        fi
      done
      [ -n "${restored_boot}" ] && imgldr_do_reboot
    else
      imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "    BOOT folder not found!" "   boot partition might be" "          outdated..."
    fi
  fi
}

build_dirs() {
  # Build rootfs base directory structure
  mkdir -p "${ROOT_MOUNT}/CONFIG" "${ROOT_MOUNT}/IMAGES" "${ROOT_MOUNT}/USERDATA" "${ROOT_MOUNT}/RAMSTORAGE"
  mkdir -p "${ROOT_MOUNT}/USERDATA/data" "${ROOT_MOUNT}/USERDATA/work"
  mkdir -p "${ROOT_MOUNT}/RAMSTORAGE/var" "${ROOT_MOUNT}/RAMSTORAGE/daemon" "${ROOT_MOUNT}/RAMSTORAGE/home"
  chown -fR 0:0 "${ROOT_MOUNT}/CONFIG" "${ROOT_MOUNT}/IMAGES"
  chmod -fR u=rwX,g=rX,o=rX "${ROOT_MOUNT}/CONFIG" "${ROOT_MOUNT}/IMAGES"
  chown -f 0:0 "${ROOT_MOUNT}/USERDATA" "${ROOT_MOUNT}/USERDATA/data" "${ROOT_MOUNT}/USERDATA/work"
  chmod -f u=rwX,g=rX,o=rX "${ROOT_MOUNT}/USERDATA" "${ROOT_MOUNT}/USERDATA/data" "${ROOT_MOUNT}/USERDATA/work"
  chown -f 0:0 "${ROOT_MOUNT}/RAMSTORAGE" "${ROOT_MOUNT}/RAMSTORAGE/var" "${ROOT_MOUNT}/RAMSTORAGE/daemon" "${ROOT_MOUNT}/RAMSTORAGE/home"
  chmod -f u=rwX,g=rwX,o=rX "${ROOT_MOUNT}/RAMSTORAGE" "${ROOT_MOUNT}/RAMSTORAGE/var" "${ROOT_MOUNT}/RAMSTORAGE/daemon" "${ROOT_MOUNT}/RAMSTORAGE/home"
  if [ "$IMGLDR_MODE" = "DEVELOPER" ]; then
    imgldr_pretty_text "       !!! WARNING !!!" "  YOU ARE IN DEVELOPER MODE!" "  Changes here will be saved" " separated from other modes!"  "And removed after leaving it!"
    mkdir -p "${ROOT_MOUNT}/DEVELOPER"
    chown -f 0:0 "${ROOT_MOUNT}/DEVELOPER"
    chmod -f u=rwX,g=rX,o=rX "${ROOT_MOUNT}/DEVELOPER"
  elif [ -d "${ROOT_MOUNT}/DEVELOPER" ]; then
    imgldr_pretty_text "       !!! WARNING !!!" "   LEAVING DEVELOPER MODE!" "   Developer folder and its" "contents will be removed now!"
    rm -rf "${ROOT_MOUNT}/DEVELOPER"
  fi
}

doing_reset() {
  if [ "$IMGLDR_RESET" != "NONE" ]; then
    local reset_type="userdata"
    [ "$IMGLDR_RESET" = "CONFIG" ] && reset_type="config"
    [ "$IMGLDR_RESET" = "ALL" ] && reset_type="factory"
    imgldr_pretty_text "     !!! SYSTEM RESET !!!" "   $reset_type reset..." "   Please wait and do not" "         power off!"
    if [ "$IMGLDR_RESET" = "USER" ]; then 
      rm -rf "${ROOT_MOUNT}/USERDATA/"*
      rm -rf "${ROOT_MOUNT}/RAMSTORAGE/"*
    fi
    [ "$IMGLDR_RESET" = "CONFIG" ] && rm -rf "${ROOT_MOUNT}/CONFIG/"*
    if [ "$IMGLDR_RESET" = "ALL" ]; then 
      rm -rf "${ROOT_MOUNT}/USERDATA/"*
      rm -rf "${ROOT_MOUNT}/RAMSTORAGE/"*
      rm -rf "${ROOT_MOUNT}/CONFIG/"*
    fi
    rm -f "${ROOT_MOUNT}/CONFIG/reset" >/dev/null 2>&1
    echo "NONE" > "${ROOT_MOUNT}/CONFIG/reset"
    echo "Reset Finished..."
    imgldr_do_reboot
  fi
  if [ "$IMGLDR_MODE" != "DEVELOPER" ] && [ -d "${ROOT_MOUNT}/DEVELOPER" ]; then
    imgldr_pretty_text "       !!! WARNING !!!" "   LEAVING DEVELOPER MODE!" "   Developer folder and its" "contents will be removed now!"
    rm -rf "${ROOT_MOUNT}/DEVELOPER"
  fi
}

auto_reboot_addon() {
  local ramstorage_reboot="${ROOT_MOUNT}/RAMSTORAGE/daemon/auto-reboot-service_reboot"
  local userdata_reboot="${ROOT_MOUNT}/USERDATA/data/etc/auto-reboot-service_reboot"
  if [ -f "${ramstorage_reboot}" ] || ( [ -f "${userdata_reboot}" ] && [ "$IMGLDR_MODE" = "STORED" ] ); then
    imgldr_pretty_text "     !!! INFORMATION !!!" "    Unrecognized shutdown" "          appeared!" "    Rebooting once now..."
    rm -f "${ramstorage_reboot}"
    rm -f "${userdata_reboot}"
    imgldr_do_reboot
  fi
}

build_sys_mount() {
  # generate SYS_MOUNT as read-write to do necessary modifications
  local sys_overlay="/mnt/sys_overlay"
  mkdir -p "$sys_overlay"
  mount -t tmpfs tmpfs "$sys_overlay"
  mkdir -p "$sys_overlay/data" mkdir -p "$sys_overlay/work"
  local lowerdir="${SQFS_MOUNT}/SYSTEM"
  local upperdir="${sys_overlay}/data"
  local workdir="${sys_overlay}/work"
  mkdir -p "${upperdir}" "${workdir}"
  mkdir -p "$SYS_MOUNT"
  if ! mount -t overlay overlay \
      -o lowerdir="${lowerdir}",upperdir="${upperdir}",workdir="${workdir}" "${SYS_MOUNT}"; then
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "   Failed to generate sqfs" "     overlay file system"
  fi
  # copy version info to SYS_MOUNT
  mkdir -p ${SYS_MOUNT}/etc/imageinfo
  [ -f ${SQFS_MOUNT}/INFO/systeminfo ] && cp -f "${SQFS_MOUNT}/INFO/systeminfo" "${SYS_MOUNT}/etc/imageinfo/sysinfo"
  # configuring fstab in SYS_MOUNT
  mkdir -p ${SYS_MOUNT}/mnt/rootfs
  local fstab_boot=$(cat ${SYS_MOUNT}/etc/fstab 2>/dev/null)
  [ -z "$ROOT_FSTYPE" ] && ROOT_FSTYPE=$(blkid -o value -s TYPE "${ROOT_DEV}" 2>/dev/null)
  [ -z "$ROOT_FSTYPE" ] && ROOT_FSTYPE="auto"
  [ -z "${fstab_boot##*\/boot\/firmware*}" ] && boot_dir="/boot/firmware" || boot_dir="/boot"
  echo "proc                   /proc           proc    defaults                      0       0" > ${SYS_MOUNT}/etc/fstab
  echo "${BOOT_DEV}            ${boot_dir}     vfat    defaults                      0       0" >> ${SYS_MOUNT}/etc/fstab
  echo "${ROOT_DEV}            /mnt/rootfs     ${ROOT_FSTYPE}    defaults,noatime         0       0" >> ${SYS_MOUNT}/etc/fstab
  # make SYS_MOUNT read-only to prevent modifications to the base system
  if ! umount "$SYS_MOUNT" >/dev/null 2>&1; then
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "Failed to unmount sys_overlay" "       tmpfs filesystem"
  fi
  local lowerdir="${sys_overlay}/data:${SQFS_MOUNT}/SYSTEM"
  if ! mount -t overlay overlay \
      -o lowerdir="${lowerdir}" "${SYS_MOUNT}"; then
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "   Failed to finalize sqfs" "     overlay file system"
  fi
}

imgldr_check_fs
get_variables
repair_bootfs
build_dirs
doing_reset
[ -f /lib/imgldr/update ] && . /lib/imgldr/update && update_start
auto_reboot_addon
build_sys_mount

exit 0
