#!/bin/sh

[ -e /scripts/imgldr_functions ] && . /scripts/imgldr_functions || exit 1

IMGLDR_MODE="RAMDISK"
IMGLDR_RESET="NONE"
SYS_MOUNT="/mnt/sys_final"
FIRSTBOOT="NO"

get_variables() {
  if [ -f "${ROOT_MOUNT}/CONFIG/mode" ]; then
    IMGLDR_MODE="$(cat "${ROOT_MOUNT}/CONFIG/mode" 2>/dev/null)"
    if [ "$IMGLDR_MODE" != "LOCAL" ] && [ "$IMGLDR_MODE" != "RAMDISK" ] && [ "$IMGLDR_MODE" != "DEVELOPER" ] && [ "$IMGLDR_MODE" != "STORED" ]; then
      imgldr_pretty_text "     !!! CONFIG ERROR !!!" "   Invalid mode in config!" "   Defaulting to RAMDISK mode!"
      IMGLDR_MODE="RAMDISK"
    fi
    if [ "$IMGLDR_MODE" = "LOCAL" ] && [ ! -f "${ROOT_MOUNT}/sbin/init" ]; then
      imgldr_pretty_text "       !!! WARNING !!!" "     local mode selected!" "   but no local init found!" "     switching to RAMDISK!"
      IMGLDR_MODE="RAMDISK"
    fi
    [ "$IMGLDR_MODE" = "STORED" ] && imgldr_pretty_text "     !!! STORED BOOT !!!"
    [ "$IMGLDR_MODE" = "DEVELOPER" ] && imgldr_pretty_text "    !!! DEVELOPER BOOT !!!" "  Changes here will be saved" " separated from other modes!"  "And removed after leaving it!"
  fi
  if [ -f "${ROOT_MOUNT}/CONFIG/reset" ]; then
    IMGLDR_RESET="$(cat "${ROOT_MOUNT}/CONFIG/reset" 2>/dev/null)"
    if [ "$IMGLDR_RESET" != "USER" ] && [ "$IMGLDR_RESET" != "CONFIG" ] && 
       [ "$IMGLDR_RESET" != "ALL" ] && [ "$IMGLDR_RESET" != "NONE" ]; then
      imgldr_pretty_text "     !!! CONFIG ERROR !!!" "   Invalid reset in config!" "   Ignoring USER reset!"
      IMGLDR_RESET="NONE"
    fi
  fi
  for x in $(cat /proc/cmdline)
  do
    case $x in
      FIRSTBOOT|*firstboot*|resize)
        FIRSTBOOT="YES"
      ;;
    esac
  done
  mkdir -p /conf
  touch /conf/param.conf
  echo "IMGLDR_MODE=$IMGLDR_MODE" >> "/conf/param.conf"
  echo "IMGLDR_RESET=$IMGLDR_RESET" >> "/conf/param.conf"
  echo "FIRSTBOOT=$FIRSTBOOT" >> "/conf/param.conf"
  echo "SYS_MOUNT=$SYS_MOUNT" >> "/conf/param.conf"
}

repair_bootfs() {
  local restored_boot
  local filepath
  local filename
  if [ "$IMGLDR_MODE" != "DEVELOPER" ]; then
    if [ -d ${SQFS_MOUNT}/BOOT ]; then
      for filepath in ${SQFS_MOUNT}/BOOT/*; do
        filename=$(basename "${filepath}")
        if [ -f "${filepath}" ] && ! diff "${filepath}" "${BOOT_MOUNT}/${filename}" >/dev/null 2>&1; then
          [ -z "${restored_boot}" ] && imgldr_pretty_text "Restore boot partition data..." "      Then Rebooting..."
          cp -f "${filepath}" "${BOOT_MOUNT}/${filename}"
          restored_boot="yes"
        fi
      done
      for filepath in ${SQFS_MOUNT}/BOOT/overlays/*; do
        filename=$(basename "${filepath}")
        if [ -f "${filepath}" ] && ! diff "${filepath}" "${BOOT_MOUNT}/overlays/${filename}" >/dev/null 2>&1; then
          [ -z "${restored_boot}" ] && imgldr_pretty_text "Restore boot partition data..." "      Then Rebooting..."
          cp -f "${filepath}" "${BOOT_MOUNT}/overlays/${filename}"
          restored_boot="yes"
        fi
      done
      [ -n "${restored_boot}" ] && imgldr_do_reboot
    else
      imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "    BOOT folder not found!" "   boot partition might be" "          outdated..."
    fi
  fi
}

build_dirs() {
  # Build rootfs base directory structure
  mkdir -p "${ROOT_MOUNT}/CONFIG" "${ROOT_MOUNT}/IMAGES" "${ROOT_MOUNT}/USERDATA" "${ROOT_MOUNT}/RAMSTORAGE"
  mkdir -p "${ROOT_MOUNT}/USERDATA/data" "${ROOT_MOUNT}/USERDATA/work"
  mkdir -p "${ROOT_MOUNT}/RAMSTORAGE"
  chown -fR 0:0 "${ROOT_MOUNT}/CONFIG" "${ROOT_MOUNT}/IMAGES"
  chmod -fR u=rwX,g=rX,o=rX "${ROOT_MOUNT}/CONFIG" "${ROOT_MOUNT}/IMAGES"
  chown -f 0:0 "${ROOT_MOUNT}/USERDATA" "${ROOT_MOUNT}/USERDATA/data" "${ROOT_MOUNT}/USERDATA/work"
  chmod -f u=rwX,g=rX,o=rX "${ROOT_MOUNT}/USERDATA" "${ROOT_MOUNT}/USERDATA/data" "${ROOT_MOUNT}/USERDATA/work"
  chown -f 0:0 "${ROOT_MOUNT}/RAMSTORAGE" "${ROOT_MOUNT}/RAMSTORAGE"
  chmod -f u=rwX,g=rX,o=rX "${ROOT_MOUNT}/RAMSTORAGE" "${ROOT_MOUNT}/RAMSTORAGE"
  if [ "$IMGLDR_MODE" = "DEVELOPER" ]; then
    mkdir -p "${ROOT_MOUNT}/DEVELOPER"
    chown -f 0:0 "${ROOT_MOUNT}/DEVELOPER"
    chmod -f u=rwX,g=rX,o=rX "${ROOT_MOUNT}/DEVELOPER"
  elif [ -d "${ROOT_MOUNT}/DEVELOPER" ]; then
    imgldr_pretty_text "       !!! WARNING !!!" "   LEAVING DEVELOPER MODE!" "   Developer folder and its" "contents will be removed now!"
    rm -rf "${ROOT_MOUNT}/DEVELOPER"
  fi
}

doing_reset() {
  if [ "$IMGLDR_RESET" != "NONE" ]; then
    local reset_type="userdata"
    [ "$IMGLDR_RESET" = "CONFIG" ] && reset_type="config"
    [ "$IMGLDR_RESET" = "ALL" ] && reset_type="factory"
    imgldr_pretty_text "     !!! SYSTEM RESET !!!" "   $reset_type reset..." "   Please wait and do not" "         power off!"
    if [ "$IMGLDR_RESET" = "USER" ]; then 
      rm -rf "${ROOT_MOUNT}/USERDATA/"*
      rm -rf "${ROOT_MOUNT}/RAMSTORAGE/"*
    fi
    [ "$IMGLDR_RESET" = "CONFIG" ] && rm -rf "${ROOT_MOUNT}/CONFIG/"*
    if [ "$IMGLDR_RESET" = "ALL" ]; then 
      rm -rf "${ROOT_MOUNT}/USERDATA/"*
      rm -rf "${ROOT_MOUNT}/RAMSTORAGE/"*
      rm -rf "${ROOT_MOUNT}/CONFIG/"*
    fi
    rm -f "${ROOT_MOUNT}/CONFIG/reset" >/dev/null 2>&1
    echo "NONE" > "${ROOT_MOUNT}/CONFIG/reset"
    echo "Reset Finished..."
    imgldr_do_reboot
  fi
  if [ "$IMGLDR_MODE" != "DEVELOPER" ] && [ -d "${ROOT_MOUNT}/DEVELOPER" ]; then
    imgldr_pretty_text "       !!! WARNING !!!" "   LEAVING DEVELOPER MODE!" "   Developer folder and its" "contents will be removed now!"
    rm -rf "${ROOT_MOUNT}/DEVELOPER"
  fi
}

auto_reboot_addon() {
  local auto_reboot="$(cat "${ROOT_MOUNT}/RAMSTORAGE/auto-reboot_boot.state" 2>/dev/null)"
  if [ "${auto_reboot}" = "bootup" ]; then
    imgldr_pretty_text "     !!! INFORMATION !!!" "    Unrecognized shutdown" "          appeared!" "    Rebooting once now..."
    echo "shutdown" > "${ROOT_MOUNT}/RAMSTORAGE/auto-reboot_boot.state"
    imgldr_do_reboot
  fi
}

initramfs_splash_addon() {
  # add initramfs-splash plymouth theme to SYS_MOUNT if configured and available
  local splashpth="/etc/splash"
  local splashimg="splash.png"
  local splashply="inactive"
  local splashopt="center"
  if [ -f "$splashpth/splash.config" ]; then
    splashimg=$(sed -n 's/^[[:space:]]*imagefile[[:space:]]*=[[:space:]]*//p' "$splashpth/splash.config" | head -n1)
    [ -z "$splashimg" ] && splashimg="splash.png"
    [ "$(sed -n 's/^[[:space:]]*plymouth[[:space:]]*=[[:space:]]*//p' "$splashpth/splash.config" | head -n1)" = "1" ] && splashply="active"
    [ "$(sed -n 's/^[[:space:]]*fullscreen[[:space:]]*=[[:space:]]*//p' "$splashpth/splash.config" | head -n1)" = "1" ] && splashopt="fullscreen"
    [ "$(sed -n 's/^[[:space:]]*stretch[[:space:]]*=[[:space:]]*//p' "$splashpth/splash.config" | head -n1)" = "1" ] && splashopt="stretch"
  else
    return
  fi
  [ "$splashply" = "inactive" ] && return
  [ ! -f "$splashpth/splash_script" ] && return
  [ ! -f "$splashpth/splash_plymouth" ] && return
  [ ! -f "$splashpth/$splashimg" ] && return
  [ ! -d "${SYS_MOUNT}/usr/share/plymouth/themes" ] && return
  [ "$IMGLDR_MODE" = "DEVELOPER" ] && imgldr_pretty_text "    Plymouth splash screen" "    from initramfs-splash" "     will not be applied" "      in developer mode!" && return
  mkdir -p "${SYS_MOUNT}/usr/share/plymouth/themes/initramfs-splash" >/dev/null 2>&1
  cp -f "$splashpth/splash_script" "${SYS_MOUNT}/usr/share/plymouth/themes/initramfs-splash/initramfs-splash.script" >/dev/null 2>&1
  cp -f "$splashpth/splash_plymouth" "${SYS_MOUNT}/usr/share/plymouth/themes/initramfs-splash/initramfs-splash.plymouth" >/dev/null 2>&1
  cp -f "$splashpth/$splashimg" "${SYS_MOUNT}/usr/share/plymouth/themes/initramfs-splash/$splashimg" >/dev/null 2>&1
  sed -i 's#^[[:space:]]*imagefile[[:space:]]*=.*#imagefile = "'"$splashimg"'";#' \
    "${SYS_MOUNT}/usr/share/plymouth/themes/initramfs-splash/initramfs-splash.script" >/dev/null 2>&1
  sed -i 's#^[[:space:]]*mode[[:space:]]*=.*#mode = "'"$splashopt"'";#' \
    "${SYS_MOUNT}/usr/share/plymouth/themes/initramfs-splash/initramfs-splash.script" >/dev/null 2>&1
  echo "[Daemon]" > "${SYS_MOUNT}/etc/plymouth/plymouthd.conf"
  echo "Theme=initramfs-splash" >> ${SYS_MOUNT}/etc/plymouth/plymouthd.conf
  echo "1" > "${SYS_MOUNT}/usr/share/plymouth/themes/initramfs-splash/plymouth_forced"
}

rpi_spinner_addon() {
  # sync plymouth-rpi-spinner with fbsplash
  local splashpth="/etc/splash"
  local splashimg="splash.png"
  if [ -f "$splashpth/splash.config" ]; then
    splashimg=$(sed -n 's/^[[:space:]]*imagefile[[:space:]]*=[[:space:]]*//p' "$splashpth/splash.config" | head -n1)
    [ -z "$splashimg" ] && splashimg="splash.png"
  fi
  [ ! -f "$splashpth/$splashimg" ] && return
  [ ! -f "${SYS_MOUNT}/usr/share/plymouth/themes/rpi-spinner/rpi-spinner.script" ] && return
  cp -f "$splashpth/$splashimg" "${SYS_MOUNT}/usr/share/plymouth/themes/rpi-spinner/$splashimg"
  sed -i "s/LOGO.PNG/${splashimg}/g" "${SYS_MOUNT}/usr/share/plymouth/themes/rpi-spinner/rpi-spinner.script"
}

ramstorage_addon() {
  #create dirs and ramstorage script
  mkdir -p "${SYS_MOUNT}/var/imgldr/config"
  mkdir -p "${SYS_MOUNT}/var/imgldr/ramstorage"
  tee /usr/local/bin/create-user-link > /dev/null <<'EOF'
#!/bin/sh
USER_NAME="$PAM_USER"
HOME_DIR="$(getent passwd "$USER_NAME" | cut -d: -f6)"
TARGET="/var/imgldr/ramstorage/userhome/$USER_NAME"
LINK="$HOME_DIR/persistent_storage"
[ -n "$USER_NAME" ] || exit 0
[ -n "$HOME_DIR" ] || exit 0
[ -d "$HOME_DIR" ] || exit 0
mkdir -p "$TARGET"
chown -f "$USER_NAME":"$USER_NAME" "$TARGET"
rm -fR "$LINK"
ln -s "$TARGET" "$LINK"
exit 0
EOF
  chmod +x /usr/local/bin/create-user-link
}

build_sys_mount() {
  # generate SYS_MOUNT as read-write to do necessary modifications
  local sys_overlay="/mnt/sys_overlay"
  mkdir -p "$sys_overlay"
  mount -t tmpfs tmpfs "$sys_overlay"
  mkdir -p "$sys_overlay/data" mkdir -p "$sys_overlay/work"
  local lowerdir="${SQFS_MOUNT}/SYSTEM"
  local upperdir="${sys_overlay}/data"
  local workdir="${sys_overlay}/work"
  mkdir -p "${upperdir}" "${workdir}"
  mkdir -p "${SYS_MOUNT}"
  if ! mount -t overlay overlay \
      -o lowerdir="${lowerdir}",upperdir="${upperdir}",workdir="${workdir}" "${SYS_MOUNT}"; then
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "   Failed to generate sqfs" "     overlay file system"
  fi
  # RUN PREPARATION STEPS ON SYS_MOUNT HERE BEFORE REMOUNTING IT AS READ-ONLY
  rpi_spinner_addon
  initramfs_splash_addon
  ramstorage_addon
  # make SYS_MOUNT read-only to prevent modifications to the base system
  if ! umount "${SYS_MOUNT}" >/dev/null 2>&1; then
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "Failed to unmount sys_overlay" "       tmpfs filesystem"
  fi
  local lowerdir="${sys_overlay}/data:${SQFS_MOUNT}/SYSTEM"
  if ! mount -t overlay overlay \
      -o lowerdir="${lowerdir}" "${SYS_MOUNT}"; then
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "   Failed to finalize sqfs" "     overlay file system"
  fi
}

imgldr_check_fs
get_variables
repair_bootfs
build_dirs
doing_reset
[ -f /lib/imgldr/update ] && . /lib/imgldr/update && update_start
auto_reboot_addon
build_sys_mount

exit 0
